apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: northwindstore
    component: app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
  type: LoadBalancer